# Activity 2:
## Gaussian Eliminiation and LU Factorizations

In [ ]:
import numpy as np

In this activity, we will work to build an LU factorization algorithm from the ground up using only the most basic of built-in numpy commands. First, we'll review some array manipulation.

In [ ]:
A=np.array([[1,2,4,-3],[2,6,1,7],[-0.5,9,3,3],[-1,2,-4,3]])

You can change the elements of an array individually like so:

In [ ]:
B=A.copy()
print("B=\n",B)#print B readably
B[0][0]=-99 #change the upper-leftmost entry to -99
B[2][3]=99 #change the entry in the third row, fourth column to 99 (remember the python indexing)
print("B=\n",B) #print B again. notice the changes

(recall the python indexing conventions: the top row/leftmost column are row/column zero)

Arithmetic operations performed on arrays (or rows of arrays)are performed element-wise. For example:

In [ ]:
B=A.copy()
B[3]=4*A[2] #change the fourth row of B to be four tiems the third row of A
print("A=\n", A,"\nB=\n",B) #display A and B readably
C=np.identity(4)-3*A #construct a new matrix given as the difference between the identity matrix and 4 times A
print("C=\n",C) #display C readably


You can also reference rows or elements of the same array.

In [ ]:
B=A.copy()
print("B=\n",B)
B[0]=3*B[1]
print("B=\n",B)
B[1]=B[0][3]*B[1]
print("B=\n",B)

You can also swap rows of an array with double-index notation. #TODO figure out if that's the right terminology

In [ ]:
B=A.copy()
print("B=\n",B)
B[[0,3]]=B[[3,0]]
print("B=\n",B)
B[[1,2,3]]=B[[3,1,2]]
print("B=\n",B)

You try: copy $A$ (from above) to a new array $B$. move the bottom row to the top and shift the other rows down. Then, negate the new bottom row and multiply the new top row by $2$. Then, let $C=B-A$.

In [ ]:
B=?

C=?

print("A=\n",A,"B=\n",B,"C=\n",C)
#desired output:
#C=
#[[ -3.    2.  -12.    9. ]
# [ -1.   -4.    3.  -10. ]
# [  2.5  -3.   -2.    4. ]
# [  1.5 -11.    1.   -6. ]]



## Regular Gaussian Elimination
First, let's build an function to perform Gaussian Elimination in the case of a regular matrix.
You are free to build your algorithm as you see fit (without using built-in functions which do the hard part for you), but here is a basic outline of one:
* Set a variable n for the size of `A` using the `shape` method. `A.shape` returns a tuple with the dimensions of `A`, so if `A` is $n\times n$, `A.shape[0]` will return `n`.
* Copy A to a new array `U` (we'll generally avoid altering the input of our functions when unnecessary)
* Use a for loop to iterate over `i` in `range(n)`. This parameter will represent the pivot we are currently working with. Then, within the for loop:
    * "Clear out" column i below the pivot `U[i][i]` by iterating with a new for loop over `j` in `range(i+1,n)`. This `j` will parametrize the row we are currently "clearing out."
        * Change the `j`th row `U[j]` by subtracting the appropriate multiple of the `i`th row `U[i]` to clear out the $(i,j)$th entry `U[i][j]`.

For the moment, we'll assume that the input is regular--don't worry about what happens in the case it is not.

In [ ]:
def my_elim(A): #The input will be a regular matrix A, encoded as a np.array
    #your code here
    return U #The outlput will be an upper-triangular matrix, also encoded as a np.array

Try out your elimination function on the test matrix below (you have our word that it's regular).

In [ ]:
A=np.array([[5., 4., 0.],
        [6., 5., 4.],
        [0., 6., 5.]])
my_elim(A)
#desired output: 
#        array([[   5. ,    4. ,    0. ],
#               [   0. ,    0.2,    4. ],
#               [   0. ,    0. , -115. ]])

## LU Factorization
Now, we'll add in code to compute the LU factorization of `A`.
First, we'll need code to construct elementary matrices.
In the cell below, define a function to give the $n\times n$ elmentary matrix $E$ where $E_{ij}=a$.

One helpful numpy built-in function is `np.identity`. Try it out in the next cell

In [ ]:
np.identity(5)

In [ ]:
def elem_matrix(n,i,j,a):
    #your code goes here
    return E

Now let's modify your `my_elim` function to produce an LU factorization of your input matrix `A`.

Some things to keep in mind:
* You still don't need to worry about the case that `A` is irregular--for now, assume it is regular. 
* The `np.dot` function performs matrix multiplication (that is, $AB$ is given by `np.dot(A,B)`).
* Page 18 of Olver-Shakiban gives the formula you'll need to form `L`.

In [ ]:
def my_LU(A):
    #your code goes here
    return (L,U)

Try it out in the next cell.

In [ ]:
A=np.array([[5., 4., 0.],
        [6., 5., 4.],
        [0., 6., 5.]])
LU(A)
#desired output:
#    (array([[ 1. ,  0. ,  0. ],
#            [ 1.2,  1. ,  0. ],
#            [ 0. , 30. ,  1. ]]),
#     array([[   5. ,    4. ,    0. ],
#            [   0. ,    0.2,    4. ],
#            [   0. ,    0. , -115. ]]))

## Exercises

### Exercise 1
So far, we haven't had to worry about the case of iregular input. However, in practice, your code needs to at least let the user know when they have entered as input an irregular matrix.
Python performs error handling by using the built-in `raise` command to raise an `Exception`, which is a message given to the user to inform them what's gone wrong. Below is a quick demonstration:

In [ ]:
def even_division(n):
    if n%2 == 1: #check if n odd
        raise Exception("input integer is odd")
    return n//2 #divide by 2
    

In [ ]:
even_division(4)

In [ ]:
even_division(5)

**Exercise:**
In the below cell, modify your code for `my_LU` to raise an exception when the input is an irregular matrix. The `Exception` shouuld say "Input matrix irregular."

In [ ]:
def my_LU_safe(A):
    #your code here
    return (L,U)

In [ ]:
A=np.array([[i*j for j in range(5)] for i in range(5)]) #This should throw an exception
my_LU_safe(A)

### Exercise 2
One of the major use cases for LU factorization is solving systems by forward- and back- substitution, as described in Olver-Shakiban, section 1.3. 
To solve a system $A\vec{x}=\vec{b}$, this works by
* computing an LU factorization $A=LU$, 
* Solving the system $L\vec{c}=\vec{b}$
* Solving the system $U \vec{x}= \vec{c}$

**Exercise:** Below, give code which implements this using `my_LU`. Do *not* use any `numpy` built-in functions which trivialize any part of this (such as taking matrix inverses)--rather you should write code to perform the substitution manually. You may choose to proceed by writing a function for back substitution then another for forward substitution if you wish--that approach is outlined below.
Be sure to test your code before you submit!

In [ ]:
def forward_sub(L,b):
    #your code here
    return c
def back_sub(U,c):
    #your code here
    return x    

In [ ]:
def my_solver(A,b):
    #your code here
    return x

In [ ]:
#testing your code
A=np.random.rand(10,10)
b=np.random.rand(10)
x=my_solver(A,b)
Ax=np.dot(A,x)
print(Ax-b) #should get vector of zeros, or close to it.

### Exercise 3 (Challenge!)
(What do we want here? regular RREF? PA=LU?)