# Activity 4: Gram-Schmidt and the QR factorization
## Reminders
In this exercise, we'll be writing code to transform arbitrary bases of $\mathbb{R}^n$ into orthogonal bases with the Gram-Schmidt process.
We'll start by reviewing some built-in functions that will be helpful.

In [1]:
import numpy as np
from numpy import linalg as LA
from numpy import random as RA

Recall that slices allow us to work directly with columns and (in most ways) treat them as vectors. Given a numpy `array` `A`, we can extract its columns using slicing. Here are a few quick examples. 

In [2]:
A=np.array([[2., 1., 0., 0.],
       [3., 2., 1., 0.],
       [0., 3., 2., 1.],
       [0., 0., 3., 2.]])
A[:,0] #first column

array([2., 3., 0., 0.])

Note that slicing gives us a *view* rather than a *copy*. If what we really want is a copy, we can call the `copy()` method

In [3]:
A[:,0]=A[:,0]*(-2) #multiply the first column by -2
A #Now note that indeed the first column is altered

array([[-4.,  1.,  0.,  0.],
       [-6.,  2.,  1.,  0.],
       [-0.,  3.,  2.,  1.],
       [-0.,  0.,  3.,  2.]])

In [4]:
v=A[:,1].copy() #call a copy of the second column
v=v*5 #multiply v by 5
A,v #check if A has changed (and compare to v)

(array([[-4.,  1.,  0.,  0.],
        [-6.,  2.,  1.,  0.],
        [-0.,  3.,  2.,  1.],
        [-0.,  0.,  3.,  2.]]),
 array([ 5., 10., 15.,  0.]))

## Exercise 1: The Gram-Schmidt process
Now, we'll implement the Gram-Schmidt process.
We'll take the columns of an input matrix to be the basis we start with.
That is, in the notation of section 4.2 of Olver-Shakiban, we'll take the columns `A[0]`, `A[1]`, ... , `A[n-1]` of our `A` to be $\vec{w}_1,\dots, \vec{w}_n$.
Our output will be a new matrix `Q` with columns given by the Gram-Schmidt process. In the notation of section 4.2, these are $\vec{v}_1,\dots,\vec{v}_n$.

For our first pass of the Gram-Schmidt process, write a function which implements the Gram-Schmidt process for a  matrix `A` with linearly independent columns using the Gram-Schmidt formula.
You may do this however you like, but an outline is given in the hint below.
<details>
    <summary> <b> Hint: </b> (Click here to expand) </summary>
    
* Set `n` to be the number of *columns* in `A`.
* Initialize a new matrix `Q` in the shape of `A`.
* Iterate over `j` in `range(n)` parametrizing which column we are working with.
* Adapt the formula $$\vec{v}_j=\vec{w}_j-\sum_{i=1}^{j-1} \frac{\langle \vec{w}_j,\vec{v_i}\rangle}{\langle \vec{v}_i,\vec{v}_i\rangle}\vec{v}_i$$ to the naming and indexing established and use it to set the column `Q[j]`.
* Return the matrix `Q`.
    </details>

In [5]:
def my_GS(A):
    n=A.shape[1] #Set n to be the number of columns in A
    Q=A.copy()   #initialize Q
    for j in range(n):
        Q[:,j]=A[:,j]-sum([ 
                            (np.dot(A[:,j],Q[:,i])/np.dot(Q[:,i],Q[:,i]))*Q[:,i]
                            for i in range(j)]) #only sum over columns already handled
    return Q

In [6]:
#testing
A1=np.array([[1,2,3],
            [4,5,6],
            [1,-1,1],
            [0,-2,-1]],"float64")
Q=my_GS(A)
Q,np.dot(np.transpose(Q),Q)  #Question: what's special about this product?
#Desired output:
#(array([[ 1.        ,  0.83333333,  1.06432749],
#       [ 4.        ,  0.33333333, -0.37426901],
#       [ 1.        , -2.16666667,  0.43274854],
#       [ 0.        , -2.        , -0.0877193 ]]),
# array([[ 1.80000000e+01, -1.77635684e-15, -2.22044605e-16],
#        [-1.77635684e-15,  9.50000000e+00,  1.52655666e-15],
#        [-2.22044605e-16,  1.52655666e-15,  1.46783626e+00]]))

(array([[-4.        , -0.23076923, -0.30508475,  0.2755102 ],
        [-6.        ,  0.15384615,  0.20338983, -0.18367347],
        [-0.        ,  3.        , -0.03389831,  0.03061224],
        [-0.        ,  0.        ,  3.        ,  0.04081633]]),
 array([[ 5.20000000e+01,  8.88178420e-16, -8.88178420e-16,
          4.99600361e-16],
        [ 8.88178420e-16,  9.07692308e+00,  2.77555756e-16,
         -2.35922393e-16],
        [-8.88178420e-16,  2.77555756e-16,  9.13559322e+00,
         -5.41233725e-16],
        [ 4.99600361e-16, -2.35922393e-16, -5.41233725e-16,
          1.12244898e-01]]))

Your code should run and give a valid result whether `A` is square or not..
Now, copy and modify your code to give an orthonormal basis. That is, after finding each $\vec{v}_i$, set $\vec u_i=\vec v_i/\lVert{\vec v_i}\rVert$ and let the output matrix's columns `Q[0]`,`Q[1]`,...,`Q[n-1]` be $\vec u_1,\dots , \vec U_n$.

You'll likely find the built-in `numpy` command `np.linalg.norm` useful, imported for convenience as `LA.norm`.

In [7]:
def my_GS_normalized(A):
    n=A.shape[1] #Set n to be the number of columns in A
    Q=A.copy()   #initialize Q
    for j in range(n):
        Q[:,j]=A[:,j]-sum([ 
                            (np.dot(A[:,j],Q[:,i]))*Q[:,i]
                            for i in range(j)]) #only sum over columns already handled
        Q[:,j]=Q[:,j]/np.linalg.norm(Q[:,j])
    return Q

In [8]:
#testing
A=np.array([[1,2,3],
            [4,5,6],
            [1,-1,1],
            [0,-2,-1]],"float64")
Q=my_GS_normalized(A)
Q,np.dot(np.transpose(Q),Q)
#Desired output:
#(array([[ 0.23570226,  0.27036904,  0.87848929],
#        [ 0.94280904,  0.10814761, -0.30891931],
#        [ 0.23570226, -0.70295949,  0.35718795],
#        [ 0.        , -0.64888568, -0.07240296]]),
# array([[ 1.00000000e+00, -1.36129200e-16, -7.70383744e-16],
#        [-1.36129200e-16,  1.00000000e+00,  4.73463928e-16],
#        [-7.70383744e-16,  4.73463928e-16,  1.00000000e+00]]))

(array([[ 0.23570226,  0.27036904,  0.87848929],
        [ 0.94280904,  0.10814761, -0.30891931],
        [ 0.23570226, -0.70295949,  0.35718795],
        [ 0.        , -0.64888568, -0.07240296]]),
 array([[ 1.00000000e+00, -1.36129200e-16, -7.70383744e-16],
        [-1.36129200e-16,  1.00000000e+00,  4.73463928e-16],
        [-7.70383744e-16,  4.73463928e-16,  1.00000000e+00]]))

## Exercise 2: Error Handling
Modify your functions to `raise` an `exception` when a linearly independent set is given as input. 

There is one major complication to this exercise: often, numpy returns a value on the order of `10**-15` or so where mathematically we should expect zero due to rounding errors. To account for this, we should take an additional parameter `tolerance` (which is set by default to `10**(-10)`) such that we ignore any variation of magnitude less than `tolerance`. (how can you make that instruction precise?)

In [9]:
def my_GS_safe(A,tolerance=10**(-10)):
    n=A.shape[1] #Set n to be the number of columns in A
    Q=A.copy()   #initialize Q
    for j in range(n):
        Q[:,j]=A[:,j]-sum([ 
                            (np.dot(A[:,j],Q[:,i])/np.dot(Q[:,i],Q[:,i]))*Q[:,i]
                            for i in range(j)]) #only sum over columns already handled
        if LA.norm(Q[:,j])<tolerance:
            raise Exception("Linearly dependent input")
    return Q
def my_GS_normalized_safe(A,tolerance=10**(-10)):
    n=A.shape[1] #Set n to be the number of columns in A
    Q=A.copy()   #initialize Q
    for j in range(n):
        Q[:,j]=A[:,j]-sum([ 
                            (np.dot(A[:,j],Q[:,i]))*Q[:,i]
                            for i in range(j)]) #only sum over columns already handled
        if LA.norm(Q[:,j])<tolerance:
            raise Exception("Linearly dependent input")
        else:
            Q[:,j]=Q[:,j]/LA.norm(Q[:,j])
    return Q

In [10]:
#testing
A1=np.array([[1,2,3],
            [4,5,6],
            [1,-1,1],
            [0,-2,-1]],"float64")
A2=np.array([[1,2,3,0],
            [4,5,6,3],
            [1,-1,1,-1],
            [0,-2,-1,-1]],"float64")
P1=my_GS_safe(A1)
print(P1)
#UNCOMMENT THESE
#P2=my_GS_safe(A2)
#print(P2)


#Desired Output:
#[[ 1.          0.83333333  1.06432749]
# [ 4.          0.33333333 -0.37426901]
# [ 1.         -2.16666667  0.43274854]
# [ 0.         -2.         -0.0877193 ]]
#---------------------------------------------------------------------------
#Exception   
# ...
# Linearly dependent input

[[ 1.          0.83333333  1.06432749]
 [ 4.          0.33333333 -0.37426901]
 [ 1.         -2.16666667  0.43274854]
 [ 0.         -2.         -0.0877193 ]]


In [11]:
#more testing
A1=np.array([[1,2,3],
            [4,5,6],
            [1,-1,1],
            [0,-2,-1]],"float64")
A2=np.array([[1,2,3,0],
            [4,5,6,3],
            [1,-1,1,-1],
            [0,-2,-1,-1]],"float64")
Q1=my_GS_normalized_safe(A1)
print(Q1)

#########UNCOMMENT THESE

#Q2=my_GS_normalized_safe(A2)
#print(Q2)

##########

#Desired output:
#[[ 0.23570226  0.27036904  0.87848929]
# [ 0.94280904  0.10814761 -0.30891931]
# [ 0.23570226 -0.70295949  0.35718795]
# [ 0.         -0.64888568 -0.07240296]]
#
#---------------------------------------------------------------------------
#Exception
#...
#Exception: Linearly dependent input

[[ 0.23570226  0.27036904  0.87848929]
 [ 0.94280904  0.10814761 -0.30891931]
 [ 0.23570226 -0.70295949  0.35718795]
 [ 0.         -0.64888568 -0.07240296]]


## Exercise 3: The QR Factorization

Now, we want to modify our code once more to produce a QR factorization of a square input matrix. Note that `my_GS_normalized` already produces an orthogonal matrix `Q` as its output given square nonsingular input. 

**Exercise:** Modify `my_GS_normalized` to produce a QR factorization of a square input matrix `A` (or work from scratch!). The process is described on pages 197-8 of Olver-Shakiban, but you may find the "numerically stable" version on page 199 easier to implement. Be sure to check your code with tests--we should have that $A=QR$ and that $QQ^T=I$

In [12]:
def my_QR(A): #this is the page 199 option
    n=A.shape[1] #Set n to be the number of columns in A
    Q=A.copy()   #initialize Q
    R=np.zeros((n,n))
    for j in range(n):
        R[j,j]=LA.norm(Q[:,j])
        Q[:,j]=Q[:,j]/R[j,j]
        for k in range(j+1,n):
            R[j,k]=np.dot(Q[:,k],Q[:,j])
            Q[:,k]=Q[:,k]-Q[:,j]*R[j,k]
    return (Q,R)

In [13]:
#testing
A3=np.array([[1,2,3],
            [4,5,6],
            [1,-1,1]],"float64")
Q3,R3=my_QR(A3)
A3,Q3,R3,np.dot(Q3,R3),np.dot(np.transpose(Q3),Q3)
#Desired output:
#(array([[ 1.,  2.,  3.],
#        [ 4.,  5.,  6.],
#        [ 1., -1.,  1.]]),
# array([[ 0.23570226,  0.35533453,  0.90453403],
#        [ 0.94280904,  0.14213381, -0.30151134],
#        [ 0.23570226, -0.92386977,  0.30151134]]),
# array([[4.24264069, 4.94974747, 6.59966329],
#        [0.        , 2.34520788, 0.99493668],
#        [0.        , 0.        , 1.20604538]]),
# array([[ 1.,  2.,  3.],
#        [ 4.,  5.,  6.],
#        [ 1., -1.,  1.]]),
# array([[ 1.00000000e+00, -5.25448946e-16, -4.12858351e-16],
#        [-5.25448946e-16,  1.00000000e+00, -9.74257535e-18],
#        [-4.12858351e-16, -9.74257535e-18,  1.00000000e+00]]))

(array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 1., -1.,  1.]]),
 array([[ 0.23570226,  0.35533453,  0.90453403],
        [ 0.94280904,  0.14213381, -0.30151134],
        [ 0.23570226, -0.92386977,  0.30151134]]),
 array([[4.24264069, 4.94974747, 6.59966329],
        [0.        , 2.34520788, 0.99493668],
        [0.        , 0.        , 1.20604538]]),
 array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 1., -1.,  1.]]),
 array([[ 1.00000000e+00, -5.25448946e-16, -4.12858351e-16],
        [-5.25448946e-16,  1.00000000e+00, -9.74257535e-18],
        [-4.12858351e-16, -9.74257535e-18,  1.00000000e+00]]))

In [14]:
def my_QR2(A): #This is the uglier (page 197-198) version
    n=A.shape[1]
    Q=A.copy()
    R=np.zeros((n,n))
    R[0,0]=LA.norm(Q[:,0])
    Q[:,0]=Q[:,0]*(1/R[0,0])
    for j in range(1,n):
        for i in range(j):
            R[i,j]=np.dot(A[:,j],Q[:,i])
        R[j,j]=np.sqrt(LA.norm(A[:,j])**2
                                      -sum(R[:,j]**2))
        Q[:,j]=(A[:,j]-sum([
            R[i,j]*Q[:,i] for i in range(j)
        ]))*(1/R[j,j])
    return Q,R
            
    

In [15]:
A3=np.array([[1,2,3],
            [4,5,6],
            [1,-1,1]],"float64")
Q3,R3=my_QR2(A3)
A3,Q3,R3,np.dot(Q3,R3),np.dot(np.transpose(Q3),Q3)
#Desired output:
#(array([[ 1.,  2.,  3.],
#        [ 4.,  5.,  6.],
#        [ 1., -1.,  1.]]),
# array([[ 0.23570226,  0.35533453,  0.90453403],
#        [ 0.94280904,  0.14213381, -0.30151134],
#        [ 0.23570226, -0.92386977,  0.30151134]]),
# array([[4.24264069, 4.94974747, 6.59966329],
#        [0.        , 2.34520788, 0.99493668],
#        [0.        , 0.        , 1.20604538]]),
# array([[ 1.,  2.,  3.],
#        [ 4.,  5.,  6.],
#        [ 1., -1.,  1.]]),
# array([[ 1.00000000e+00, -5.25448946e-16, -4.12858351e-16],
#        [-5.25448946e-16,  1.00000000e+00, -9.74257535e-18],
#        [-4.12858351e-16, -9.74257535e-18,  1.00000000e+00]]))

(array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 1., -1.,  1.]]),
 array([[ 0.23570226,  0.35533453,  0.90453403],
        [ 0.94280904,  0.14213381, -0.30151134],
        [ 0.23570226, -0.92386977,  0.30151134]]),
 array([[4.24264069, 4.94974747, 6.59966329],
        [0.        , 2.34520788, 0.99493668],
        [0.        , 0.        , 1.20604538]]),
 array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 1., -1.,  1.]]),
 array([[ 1.00000000e+00, -5.43680314e-16, -7.09824319e-16],
        [-5.43680314e-16,  1.00000000e+00,  1.83601527e-15],
        [-7.09824319e-16,  1.83601527e-15,  1.00000000e+00]]))

## Exercise 4: Orthogonal Projection
Recall from Olver-Shakiban:
**Definition 4.31.** The *orthogonal projection* of $\vec v$ onto the subspace $W$ is the element $\vec w \in W$ such that $\vec z = \vec v - \vec w$ is orthogonal to $W$.

Note that Theorem 4.32 below it gives a formula for $\vec w$ in terms of an orthonormal basis for $W$.

**Exercise** Given a basis for $W$ (in the form of the columns of an array `A`) and a vector `v`, write a function `my_projection` which outputs the orthogonal projection `w` of `v` onto `W`.

In [16]:
def my_projection(A,v):
    Q=my_GS_normalized(A)
    n=Q.shape[1] #number of columns in Q
    cs= np.array([np.dot(v,Q[:,i]) for i in range(n)])#construct vector of constants c_i
    w=np.dot(Q,cs)
    return w

In [17]:
#testing
A1=np.array([[1,2,3],
            [4,5,6],
            [1,-1,1],
            [0,-2,-1]],"float64")
v=np.array([1,0,0,0],"float64")
w=my_projection(A1,v)
z=v-w
w,z,np.dot(np.transpose(A1),z)
#Desired output:
#(array([ 0.90039841, -0.01992032,  0.17928287, -0.23904382]),
# array([ 0.09960159,  0.01992032, -0.17928287,  0.23904382]),
# array([2.72004641e-15, 1.83186799e-15, 3.83026943e-15]))
#(or something very close to zero for the third line)

(array([ 0.90039841, -0.01992032,  0.17928287, -0.23904382]),
 array([ 0.09960159,  0.01992032, -0.17928287,  0.23904382]),
 array([2.72004641e-15, 1.83186799e-15, 3.83026943e-15]))

## Exercise 5 (Challenge!): Comparing the approaches
In exercise 2, two QR algorithms were suggested to you, one on pages 197-98 and one on page 199 of Olver-Shakiban. 

**(a)** Whichever one you did *not* implement, implement that one below as `my_QR2`.

In [18]:
def my_QR2(A): #This is the uglier (page 197-198) version
    n=A.shape[1]
    Q=A.copy()
    R=np.zeros((n,n))
    R[0,0]=np.linalg.norm(Q[:,0])
    Q[:,0]=Q[:,0]*(1/R[0,0])
    for j in range(1,n):
        for i in range(j):
            R[i,j]=np.dot(A[:,j],Q[:,i])
        R[j,j]=np.sqrt(np.linalg.norm(A[:,j])**2
                                      -sum(R[:,j]**2))
        Q[:,j]=(A[:,j]-sum([
            R[i,j]*Q[:,i] for i in range(j)
        ]))*(1/R[j,j])
    return Q,R

**(b)** Write a function which measures failure of orthogonality of an input matrix $Q$ by giving the greatest entry of $\left\lvert Q^TQ-I\right \rvert$ where $I$ is the appropriately-sized identity matrix. 

*Note:* You might find issues if you try to use the base python built-in `max`. There are workarounds for this, but the best solution is probably the `numpy`-provided `np.max`.

In [19]:
def orth_checker(Q):
    n=Q.shape[1]
    return np.max(abs(np.dot(np.transpose(Q),Q)-np.identity(n)))

In [20]:
M=RA.rand(5,5)
(Q,R)=my_QR(M)
orth_checker(Q)

1.0085695272043962e-14

**(c):** `np.random.rand(m,n)` (imported for convenience as `RA.rand(m,n)`) returns a random matrix of dimensions $m\times n$ with entries in the interval $[0,1)$. Use this to write a function which takes as input a dimension `n` and a number of iterations `num_iters` and compares your two implementations by generating a random $n\times n$ matrix, using both QR algorithms to compute a factorization, and checking which returns a $Q$ closer to being on-the-nose orthogonal, doing this `num_iters` times. When run, your function should print a line for each test stating which iteration the test is on, which implementation gave a result with better `orth_checker` result, and that `orth_checker` result. Finally, when the test is concluded, print out how many times each algorithm 'won' in human-readable form.

In [21]:
def QR_comp(n,num_iters):
    QR1_score=0
    QR2_score=0
    for k in range(num_iters):
        M=RA.rand(n,n)
        Q1,R1=my_QR(M)
        Q2,R2=my_QR2(M)
        d1=orth_checker(Q1)
        d2=orth_checker(Q2)
        if d1>d2:
            QR2_score+=1
            print("iteration ", k+1," my_QR2 better, orth_checker = ", d2)
        elif d2>d1:
            QR1_score+=1
            print("iteration ", k+1," my_QR better, orth_checker = ", d1)
    if QR1_score>QR2_score:
        print("my_QR better overall, preferred in ",QR1_score," trials out of ",num_iters)
    elif QR1_score>QR2_score:
        print("my_QR2 better overall, preferred in ",QR2_score," trials out of ",num_iters)
    return

In [22]:
QR_comp(2, 80)

iteration  1  my_QR better, orth_checker =  3.2986277793410147e-16
iteration  2  my_QR better, orth_checker =  3.0305680881220174e-15
iteration  3  my_QR better, orth_checker =  1.1102230246251565e-16
iteration  4  my_QR better, orth_checker =  3.634908580454884e-16
iteration  5  my_QR better, orth_checker =  2.220446049250313e-16
iteration  6  my_QR better, orth_checker =  2.220446049250313e-16
iteration  7  my_QR better, orth_checker =  5.33065834487526e-16
iteration  8  my_QR better, orth_checker =  3.064649022861732e-17
iteration  9  my_QR2 better, orth_checker =  2.750440559930564e-18
iteration  10  my_QR better, orth_checker =  1.324227365129846e-16
iteration  11  my_QR better, orth_checker =  2.305259863142594e-16
iteration  12  my_QR better, orth_checker =  1.873308840547904e-15
iteration  13  my_QR better, orth_checker =  2.2793235828162075e-16
iteration  16  my_QR2 better, orth_checker =  2.5220323004561075e-16
iteration  17  my_QR better, orth_checker =  2.46206484938364e-16

(d) Try your comparison function with varying `n` and a large `num_iters`. Is one consistently better than the other? Do the results change in low or high dimension? Write a few words below. You might consider modifying your code to track how much closer to orthogonality the preferred one is compared to the other, perhaps computing the largest and average discrepancies.

(This is an empty markdown cell for you to type out your response)

The numerically stable one should definitely perform better. Most likely, the student will find that the numerically stable version compares better most of the time in low dimension and every single time (or close to it) in higher dimension. They will probably also note that it performs worse the higher the dimension.

In [23]:
def QR_diff(n,num_iters):
    QR1_score=0
    QR2_score=0
    tot_diff=0
    max_diff=-np.inf
    min_diff=np.inf
    for k in range(num_iters):
        M=RA.rand(n,n)
        Q1,R1=my_QR(M)
        Q2,R2=my_QR2(M)
        d1=orth_checker(Q1)
        d2=orth_checker(Q2)
        tot_diff+=d2-d1
        if d2-d1>max_diff:
            max_diff=d2-d1
        if d2-d1<min_diff:
            min_diff=d2-d1
        if d1>d2:
            QR2_score+=1
            #print("iteration ", k+1," my_QR2 better, orth_checker = ", d2," difference of ",d1-d2)
        elif d2>d1:
            QR1_score+=1
            #print("iteration ", k+1," my_QR better, orth_checker = ", d1," difference of ",d2-d1)
    if QR1_score>QR2_score:
        print("my_QR better overall, preferred in ",QR1_score," trials out of ",num_iters, "\n average difference of ",tot_diff/num_iters," max discrepancy of ",max_diff)
    elif QR1_score>QR2_score:
        print("my_QR2 better overall, preferred in ",QR2_score," trials out of ",num_iters, "\n average difference of ",-tot_diff/num_iters," max discrepancy of ",-min_diff )
    return

In [24]:
QR_diff(2,1000)

my_QR better overall, preferred in  799  trials out of  1000 
 average difference of  1.6436603289915847e-13  max discrepancy of  9.513935054359707e-11


In [25]:
QR_diff(10, 1000)

my_QR better overall, preferred in  1000  trials out of  1000 
 average difference of  3.3295625821234895e-11  max discrepancy of  1.7103510218308668e-08


In [26]:
QR_diff(100, 100)

my_QR better overall, preferred in  100  trials out of  100 
 average difference of  1.7965104595940908e-07  max discrepancy of  1.7907453356321796e-05
